# typed: false
# frozen_string_literal: true
#
# Auto-generated by sv-tools/roas .github/workflows/publish.yaml.
# Do not edit by hand — changes are overwritten on the next release.
class Roas < Formula
  desc "Command-line front-end for the roas OpenAPI library"
  homepage "https://github.com/sv-tools/roas"
  version "0.11.0"
  license any_of: ["MIT", "Apache-2.0"]

  on_macos do
    on_arm do
      url "https://github.com/sv-tools/roas/releases/download/roas-cli/v0.11.0/roas-0.11.0-aarch64-apple-darwin.tar.gz"
      sha256 "63ff69915ba93d8884fb28e252278d373beafa937f519aa4a11233097f518b71"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/sv-tools/roas/releases/download/roas-cli/v0.11.0/roas-0.11.0-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "6485bd337a4a93b2444c5afd5f0db3cff173764ed433c883b70f29ffcd14e629"
    end
    on_intel do
      url "https://github.com/sv-tools/roas/releases/download/roas-cli/v0.11.0/roas-0.11.0-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "f23f3a70ab49dda7e93cfe92fdbfdd5721851cac40202b24e723ba3781d9e2c9"
    end
  end

  def install
    bin.install "roas"
    # Generate shell completions + manpages from the binary we
    # just installed — no extra tarball download required.
    generate_completions_from_executable(bin/"roas", "completions")
    man_dir = buildpath/"man"
    system bin/"roas", "manpages", "--out", man_dir
    man1.install Dir[man_dir/"*.1"]
  end

  test do
    assert_match "roas 0.11.0", shell_output("#{bin}/roas --version")
  end
end
