# typed: false
# frozen_string_literal: true
#
# Auto-generated by sv-tools/roas .github/workflows/publish.yaml.
# Do not edit by hand — changes are overwritten on the next release.
class Roas < Formula
  desc "Command-line front-end for the roas OpenAPI library"
  homepage "https://github.com/sv-tools/roas"
  version "0.3.0"
  license any_of: ["MIT", "Apache-2.0"]

  on_macos do
    on_arm do
      url "https://github.com/sv-tools/roas/releases/download/roas-cli/v0.3.0/roas-0.3.0-aarch64-apple-darwin.tar.gz"
      sha256 "ce592f07d31c9a016671c7df7822421ea8da3f1610b4fc8d30010bc71fe12037"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/sv-tools/roas/releases/download/roas-cli/v0.3.0/roas-0.3.0-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "a8cac3bb98b657f02536e2cf5221e116e0ad8d017fd846cfd1d8ff40bd201289"
    end
    on_intel do
      url "https://github.com/sv-tools/roas/releases/download/roas-cli/v0.3.0/roas-0.3.0-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "8512c06bb555cae445ff27218ed1e1932e345229614efcd3611b881c61345b5d"
    end
  end

  def install
    bin.install "roas"
  end

  test do
    assert_match "roas 0.3.0", shell_output("#{bin}/roas --version")
  end
end
