# typed: false
# frozen_string_literal: true
#
# Auto-generated by sv-tools/roas .github/workflows/publish.yaml.
# Do not edit by hand — changes are overwritten on the next release.
class Roas < Formula
  desc "Command-line front-end for the roas OpenAPI library"
  homepage "https://github.com/sv-tools/roas"
  version "0.6.1"
  license any_of: ["MIT", "Apache-2.0"]

  on_macos do
    on_arm do
      url "https://github.com/sv-tools/roas/releases/download/roas-cli/v0.6.1/roas-0.6.1-aarch64-apple-darwin.tar.gz"
      sha256 "47dc685517126c9b9c21318c29ed895b8da59161227b876a87b8cebca5a473dd"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/sv-tools/roas/releases/download/roas-cli/v0.6.1/roas-0.6.1-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "60db78463185665540a175cf550a700e11bf25a5cbfe9bc87f5e4d6b65461302"
    end
    on_intel do
      url "https://github.com/sv-tools/roas/releases/download/roas-cli/v0.6.1/roas-0.6.1-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "5da3eb2588bae6f991c872b7a48c54d8a283f4d60148f53e771a7f4148e63bbd"
    end
  end

  def install
    bin.install "roas"
    # Generate shell completions + manpages from the binary we
    # just installed — no extra tarball download required.
    generate_completions_from_executable(bin/"roas", "completions")
    man_dir = buildpath/"man"
    system bin/"roas", "manpages", "--out", man_dir
    man1.install Dir[man_dir/"*.1"]
  end

  test do
    assert_match "roas 0.6.1", shell_output("#{bin}/roas --version")
  end
end
